// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIrbSDxM_5WORnM4Gp8LxKcVAcH9gJLis',
    appId: '1:117551501634:web:3194af5d6dfbacb63bb8db',
    messagingSenderId: '117551501634',
    projectId: 'tpamov-33308',
    authDomain: 'tpamov-33308.firebaseapp.com',
    storageBucket: 'tpamov-33308.appspot.com',
    measurementId: 'G-MV1PC7VVC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAzNj0_bP89G4_H-2PspveGiI7QL7L3w0',
    appId: '1:117551501634:android:4bac96d9ce5756663bb8db',
    messagingSenderId: '117551501634',
    projectId: 'tpamov-33308',
    storageBucket: 'tpamov-33308.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmp__VAg_1RJ-tZjXyeD4JM6mYmrlTaPY',
    appId: '1:117551501634:ios:fca1c0739dd735c63bb8db',
    messagingSenderId: '117551501634',
    projectId: 'tpamov-33308',
    storageBucket: 'tpamov-33308.appspot.com',
    iosBundleId: 'pt.isec.a2105016870.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmp__VAg_1RJ-tZjXyeD4JM6mYmrlTaPY',
    appId: '1:117551501634:ios:c8b7dd4269bb8cb53bb8db',
    messagingSenderId: '117551501634',
    projectId: 'tpamov-33308',
    storageBucket: 'tpamov-33308.appspot.com',
    iosBundleId: 'pt.isec.a2105016870.flutterProject.RunnerTests',
  );
}
